# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3bDKc_8pvjQHva5vcqyV9bY96XEVaev
"""

import csv
from datetime import datetime
from collections import defaultdict

# Nome do arquivo CSV
filename = "financas.csv"

def adicionar_registro(data, descricao, tipo, valor):
    with open(filename, "a", newline="") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow([data, descricao, tipo, valor])

# Loop principal do chatbot
while True:
    # Obtém a entrada do usuário
    prompt = input("Olá! O que você gostaria de fazer hoje?\n"
                   "1. Adicionar Ganho\n"
                   "2. Adicionar Gasto\n"
                   "3. Consultar\n"
                   "4. Sair\n"
                   "Digite o número da opção desejada: ")

    # Processa a entrada do usuário
    if prompt == "4":
        print("Até mais! 👋")
        break
    elif prompt in ["1", "2"]:
        tipo = "Ganho" if prompt == "1" else "Gasto"
        while True:
            try:
                valor = float(input(f"Digite o valor do {tipo}: "))
                if valor <= 0:
                    raise ValueError
                break
            except ValueError:
                print("Valor inválido! Digite um número positivo.")
        descricao = input(f"Digite uma breve descrição para o {tipo}: ")
        data = datetime.now().strftime("%d/%m/%Y")
        adicionar_registro(data, descricao, tipo, valor)
        print(f"{tipo} adicionado com sucesso!")
    elif prompt == "3":
        saldo = 0
        gastos_por_categoria = defaultdict(float)
        with open(filename, "r") as csvfile:
            reader = csv.reader(csvfile)
            next(reader)  # pular o cabeçalho, se houver
            for row in reader:
                data, descricao, tipo, valor = row
                valor = float(valor)
                if tipo == "Ganho":
                    saldo += valor
                elif tipo == "Gasto":
                    saldo -= valor
                    gastos_por_categoria[descricao] += valor

        print(f"Seu saldo atual é: R${saldo:.2f}")

        gastos_ordenados = sorted(gastos_por_categoria.items(), key=lambda item: item[1], reverse=True)

        print("\nSeus maiores gastos são:")
        for descricao, valor in gastos_ordenados:
            print(f"- {descricao}: R${valor:.2f}")
    else:
        print("Opção inválida! Por favor, escolha uma opção válida.")